version: "3"
services:
    dev:
        image: "node:8.9"
        environment:
            - NODE_ENV=development
        volumes:
            - ./:/mondial-pronos
        working_dir: /mondial-pronos
        ports:
            - "3000:3000"
        command: npm start
    test:
        image: "node:8.9"
        environment:
            - NODE_ENV=test
        volumes:
            - ./:/mondial-pronos
        working_dir: /mondial-pronos
        command: npm test
    storybook:
        image: "node:8.9"
        environment:
            - NODE_ENV=development
        volumes:
            - ./:/mondial-pronos
        ports:
            - "9009:9009"
        working_dir: /mondial-pronos
        command: npm run storybook
    firebase:
        image: "node:6.11"
        environment:
            - NODE_ENV=development
        volumes:
            - ./:/mondial-pronos
            - ~/.config/configstore/:/root/.config/configstore/
        working_dir: /mondial-pronos
        ports:
            - "5000:5000"
        command: >
            sh -c '
                cd firebase &&
                npm install && 
                npm run serve
            '